version: '3.8'

services:
  web:
    container_name: flask_api
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
            - FLASK_APP=manage.py
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data: {}